name: vibe_journal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  record: ^6.0.0
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  path_provider: ^2.1.5
  haptic_feedback: ^0.5.1+1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  firebase_storage: ^12.4.6
  table_calendar: ^3.2.0
  just_audio: ^0.10.4
  flutter_sound: ^9.28.0
  fl_chart: ^1.0.0
  in_app_purchase: ^3.2.3
  cloud_functions: ^5.5.1
  rxdart: ^0.28.0

  collection: any
  firebase_messaging: ^15.2.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/