import 'package:flutter/material.dart';
import 'package:vibe_journal/core/widgets/legal_document_view.dart';

class PrivacyPolicyContent extends StatelessWidget {
  final bool showAcceptanceControls;
  final bool isCheckboxChecked;
  final ValueChanged<bool?>? onCheckboxChanged;
  final VoidCallback? onAcceptButtonPressed;
  final bool isAcceptButtonEnabled;

  const PrivacyPolicyContent({
    super.key,
    this.showAcceptanceControls = false,
    this.isCheckboxChecked = false,
    this.onCheckboxChanged,
    this.onAcceptButtonPressed,
    this.isAcceptButtonEnabled = false,
  });

  @override
  Widget build(BuildContext context) {
    return LegalDocumentView(
      title: 'Privacy Policy',
      showAcceptanceControls: showAcceptanceControls,
      isCheckboxChecked: isCheckboxChecked,
      onCheckboxChanged: onCheckboxChanged,
      onAcceptButtonPressed: onAcceptButtonPressed,
      isAcceptButtonEnabled: isAcceptButtonEnabled,
      content: '''
Last Updated: June 8, 2025

Welcome to VibeJournal. Your privacy is critically important to us.

1.  Information We Collect
    a. Account Information: When you sign up, we collect your full name and email address to create and manage your account.
    b. Audio and Text Data: We collect the audio recordings you create and the corresponding transcriptions and mood analyses generated by our service. This data is stored securely and is only accessible by you.
    c. Usage Data: We may collect anonymous data about how you interact with our app to help us improve our services.

2.  How We Use Your Information
    a. To Provide and Maintain the Service: We use your data to provide the core functionalities of VibeJournal, including storing your entries, analyzing them for mood, and providing you with insights.
    b. To Improve Our Service: Anonymous usage data helps us understand what features are popular and where we can make improvements.
    c. To Communicate With You: We may use your email address to send you important updates or information about your account.

3.  Data Storage and Security
    a. Your personal data, including audio files and transcriptions, are stored using secure cloud services (Firebase). We take all reasonable measures to protect your information from unauthorized access.

4.  Third-Party Services
    a. We use third-party services like Google Cloud for Speech-to-Text and Natural Language Processing. Your audio and text data are processed by these services to provide the analysis features. Their use of data is governed by their respective privacy policies.

5.  Your Rights
    a. You have the right to access and delete your data at any time. Account deletion will permanently remove all your associated journal entries.

6.  Changes to This Policy
    a. We may update this privacy policy from time to time. We will notify you of any significant changes.

7.  Contact Us
    a. If you have any questions about this Privacy Policy, please contact us at prantadutta1997@gmail.com.
''',
    );
  }
}
